Feature/readmore component
studiometa/ui pull request #106
Opened 2023-01-10 12:25 UTC by Liax

Objective
First draft of a Readmore component

To do:
- Add an option to enter one content and crop it
- Add the length to which it should be cropped
- Animate the reveal
- Add an option to not use the animate
- Be sure that the component is abstract and reusable.
- Add documentations

2023-01-10 15:05 UTC, titouanmathis requested changes
This is a nice first draft, well done @Liax!

2023-01-10 15:05 UTC, titouanmathis commented on packages/docs/components/molecules/Readmore/examples.md
> +:::details Code
**chore:** The `:::details` macro is not rendered correctly, maybe add an empty line before to fix this? 🤔 

You can compare to the other `examples.md` files to find what is different.

2023-01-10 15:05 UTC, titouanmathis commented on packages/ui/molecules/Readmore/Readmore.js
> +import { Base } from '@studiometa/js-toolkit';
**issue:** Migrate the file to TypeScript

I suggest that you try to do it on your own, based on the other components, and we can finish it with a pair-programming session.

2023-01-10 15:05 UTC, titouanmathis commented on packages/ui/molecules/Readmore/Readmore.js
> +    refs: ['btn', 'btnLabel', 'main_content', 'hidden_content'],
**issue:** Do not mix camelCase with snake_case, use the camelCase format for refs

2023-01-10 15:05 UTC, titouanmathis commented on packages/ui/molecules/Readmore/Readmore.js
> +    this.hiddenContent = this.$refs.hidden_content;
**issue:** Reassigning refs to other properties on the instance is not necessary here

You can directly use `this.$refs.<NAME>` here.

It also might impact performance because we are adding non-declared properties to the instance. 

```js
// Avoid
class Foo {
  anyMethod() {
    this.foo = 'foo';
  }
}

// Prefer
class Foo {
  foo;

  anyMethod() {
    this.foo = 'foo';
  }
}
```

2023-01-10 15:05 UTC, titouanmathis commented on packages/ui/molecules/Readmore/Readmore.js
> +    if (this.hiddenContent.classList.contains('hidden')) {
**suggestion:** Implement dedicated `show`, `hide` and `toggle` methods that you can use in this method

This allows us to trigger these methods directly if needed (from a parent, when extending this component, etc.).

2023-01-10 15:05 UTC, titouanmathis commented on packages/ui/molecules/Readmore/Readmore.twig
> +    {{ main_content }}
**suggestion:** Wrap the content in a block 

We can use more advanced markup when working with a block vs. a parameter.

2023-01-10 15:05 UTC, titouanmathis commented on packages/ui/molecules/Readmore/Readmore.twig
> +    {{ hidden_content }}
**suggestion:** Wrap the content in a block 

We can use more advanced markup when working with a block vs. a parameter.

2023-01-10 15:05 UTC, titouanmathis commented on packages/ui/molecules/Readmore/Readmore.twig
> +  {% include '@ui/atoms/Button/StyledButton.twig' with {
**nitpick:** Prefer using the unstyled button here as it is less opinionated by default

2024-04-19 13:13 UTC, antoine4livre commented
Nice !

2024-04-23 09:22 UTC, notjb commented on packages/ui/molecules/Readmore/Readmore.ts
> +    this.$refs.btn.innerHTML = this.$options.btnLabelMore;
**suggestion:** `innerHTML` might be unsafe. Consider using `textContent` instead 😇

2025-05-12 14:15 UTC, titouanmathis commented
This feature can be implemented with a combination of [Transition](https://ui.studiometa.dev/-/components/Transition/) and [Action](https://ui.studiometa.dev/-/components/Action/) components, or with the [`Frame` component](https://ui.studiometa.dev/-/components/Frame/) if an HTTP request is needed to fetch the content.

Closing this PR for now (but it could be re-opened in the future if needed).

2025-05-12 14:15 UTC, closed without merging